# Generated by Django 5.0.2 on 2024-02-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje_nombre', models.CharField(max_length=20)),
                ('tipo_de_poder', models.CharField(max_length=20)),
                ('daño_de_poder', models.IntegerField()),
                ('dmg_realizado', models.IntegerField()),
            ],
        ),
    ]
