# Generated by Django 5.0.2 on 2024-02-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_personaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumno',
        ),
    ]
