# Generated by Django 5.0.2 on 2024-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carta', models.CharField(max_length=20)),
                ('elemento', models.CharField(max_length=20)),
                ('daño_de_carta', models.IntegerField()),
            ],
        ),
    ]
